# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://kiah2008.github.io
date_format: "ordinal"
title: Kiah's daily work
subtitle: "Stay hungry, stay foolish!"
description: "Kiah's daily work"
keywords: audio/video technicals
timezone: Asia/Shanghai
encoding: "utf-8"

# 页面左下角显示的年份
since: 2022
# 源码仓库
repository: kiah2008/kiah2008.github.io
repo_branch: main

# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-05-03
    # My Popular Repositories
    side_bar_repo:
        enabled: false
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: true
        image_alt: kiah_pic
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate

# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Kiah Zhao
organization: 
organization_url: 
github_username: kiah2008
location: Chengdu, China
email: kiah.android@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /tags/
    label: 标签
#   -
#     href: /open-source/
#     label: 开源

#   -
#     href: /wiki/
#     label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /archives/
    label: 归档

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
#highlighter: rouge

paginate: 10
lsi: false
quiet: false
excerpt_separator: "<!-- more -->"
permalink: /:year/:month/:day/:title/
plugins:
#    - jekyll-github-metadata
#    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar
comments_provider: beaudar
# disqus 配置参考：https://disqus.com
disqus:
    username: 
# gitment 配置参考：https://imsun.net/posts/gitment-introduction/
gitment:
    owner: 
    repo: 
    oauth:
        client_id: 
        client_secret: 
# gitalk 配置参考：https://github.com/gitalk/gitalk#install
gitalk:
    owner: 
    repo: 
    clientID: 
    clientSecret: 
# utterances 配置参考：https://utteranc.es/
utterances:
    repo: kiah2008/blog_comments
# beaudar 配置参考：https://beaudar.lipk.org/
beaudar:
    repo: kiah2008/blog_comments
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: 
    adsense:
        footer: false
        sidebar: false 
        sidebar-detail: false 
        content_header: false
        content_footer: false
    data_ad_client:
    data_ad_slot:

baidu:
    tongji: 25f843956cb12e071ce88189ef762579

# cdn 加速
open_cdn:
  jquery: https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js
  jquery_ui: https://libs.baidu.com/jqueryui/1.8.22/jquery-ui.min.js
  pusuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
  mermaid: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  simple_jekyll_search: https://cdn.bootcdn.net/ajax/libs/simple-jekyll-search/1.9.2/simple-jekyll-search.min.js
  geopattern: https://cdn.bootcdn.net/ajax/libs/geopattern/1.2.3/js/geopattern.min.js
  flowchart: https://cdn.bootcdn.net/ajax/libs/flowchart/1.17.1/flowchart.min.js




